---
- name: "Copy backend files"
  become: yes
  synchronize:
    src: /
    dest: /home/ubuntu
    recursive: true

- name: "pip build"
  become: true
  shell: |
    pip install requirements.txt
  args:
    chdir: /

- name: "Deploy code"
  become: true
  shell: |
    pm2 start -f ./main.js
  args:
    chdir: /

- name: start flask
  shell: "flask run"
